Azure/aks-mcp

internal/azureclient/client.go
internal/azureclient/detector.go
internal/components/detectors/client.go
internal/components/detectors/detectors_test.go
internal/components/detectors/handlers.go
internal/components/detectors/registry.go
internal/components/detectors/types.go
internal/server/server.go

Fix #57 
- Add three new MCP tools: list_detectors, run_detector, run_detectors_by_category
- Implement detector client with caching support using Azure Management API
- Add comprehensive input validation for time parameters and categories
- Support AKS cluster resource ID format parsing
- Add unit tests for validation functions

feat: implement AppLens detector MCP tools

---

internal/components/monitor/handlers.go
internal/components/monitor/handlers_test.go
internal/components/monitor/registry.go
internal/security/validator.go
internal/server/server.go

- Implement az_monitor_app_insights_query MCP tool
- Add comprehensive KQL query safety validation
- Support time-based filtering with RFC3339/ISO 8601
- Integrate with existing security and access level framework
- Add comprehensive test suite with 26 test cases
- Support all Application Insights telemetry types
Features:
- Execute KQL queries against Application Insights telemetry data
- Query safety validation (blocks dangerous keywords)
- Parameter validation and error handling
- Time format validation (RFC3339/ISO 8601)
- Integration with readonly, readwrite, and admin access levels
- Support for all telemetry types (requests, dependencies, exceptions, etc.)
Security:
- KQL query safety checks prevent dangerous operations
- Table name validation ensures valid Application Insights …

feat: Add Azure Application Insights KQL query tool for AKS clusters

---

internal/components/monitor/diagnostics/handlers.go
internal/components/monitor/diagnostics/kql.go
internal/components/monitor/diagnostics/kql_test.go
internal/components/monitor/diagnostics/validation.go
internal/components/monitor/diagnostics/validation_test.go
internal/components/monitor/diagnostics/workspace.go
internal/components/monitor/diagnostics/workspace_test.go

This pull request introduces significant updates to enhance the handling of diagnostic settings and KQL query generation for Azure Kubernetes Service (AKS) control plane logs. The changes improve support for resource-specific tables, add flexibility in log category handling, and refactor the KQL query builder for better maintainability. Key updates include the addition of a diagnostic setting finder, a revamped query builder, and new test cases.
* Introduced the `FindDiagnosticSettingForCategory` function to locate diagnostic settings with the specified log category enabled, returning the workspace resource ID and whether resource-specific tables are used. Debug logging was added for better traceability. (`internal/components/monitor/diagnostics/workspace.go`, …

Feat: support resource-specific tables for diagnostics

---

internal/components/inspektorgadget/const.go
internal/components/inspektorgadget/handlers.go
internal/components/inspektorgadget/helpers.go

Use the latest release if available otherwise fallback to build version. This ensures users will use the latest IG release even if it was released after aks-mcp server release, to keep the behavior aligned with manual installation. 
```
$ curl -s https://api.github.com/repos/inspektor-gadget/inspektor-gadget/releases/latest | jq -r '.tag_name' | sed 's/^v//'
```

chore/inspektor-gadget: Use latest stable release if available

---

.github/workflows/ci.yml
.github/workflows/go-ossf-slsa3-publish.yml
Dockerfile
Dockerfile.windows

chore: add support for multiarch container image

---

README.md

Adding instructions for installing AKS-MCP using the AKS Extension for VSCode. Setting this as recommended and moving all manual instructions into the sub-section "Manual Binary Installation".

Add AKS Extension for VSCode installation as recommended path

---

internal/server/server.go
internal/server/server_test.go

make a clear method hierarchy
```
Initialize()
├── initializeInfrastructure()
└── registerAllComponents()
├── registerAzureComponents()
│   ├── registerAksOpsComponent()
│   ├── registerMonitoringComponent()
│   ├── registerFleetComponent()
│   ├── registerNetworkComponent()
│   ├── registerComputeComponent()
│   ├── registerDetectorComponent()
│   ├── registerAdvisorComponent()
│   └── registerInspektorGadgetComponent()
└── registerKubernetesComponents()
├── registerKubectlComponent()
└── registerOptionalKubernetesComponents()
├── registerHelmComponent()
└── registerCiliumComponent()
```

Refact: make a clear component hierarchy for tools registration

---

internal/config/validator.go
internal/server/server.go

Changed references from "MCP Kubernetes" to "AKS MCP" in log messages and comments to maintain consistent naming throughout the codebase.

fix: update log messages and comments to use AKS MCP naming

---

internal/components/monitor/diagnostics/kql.go
internal/components/monitor/diagnostics/kql_test.go

When the diagnostics setting is using the dedicated table, there are some logs (kube-*, guard, etc) except kube-audit-* share the same table AKSControlPlane.  The bug is it doesn't filter logs by categories so all logs will be returned to agent. 
This PR is to fix the problem.

Fix: filter control plane logs by categories when using  AKSControlPlane table

---

docs/inspektor-gadget-usage.md
internal/components/inspektorgadget/const.go
internal/components/inspektorgadget/gadgetmanager.go
internal/components/inspektorgadget/gadgets.go
internal/components/inspektorgadget/gadgets_test.go
internal/components/inspektorgadget/handlers.go
internal/components/inspektorgadget/handlers_test.go
internal/components/inspektorgadget/helpers.go
internal/components/inspektorgadget/helpers_test.go
internal/components/inspektorgadget/registry.go
internal/server/server.go

This PR makes changes to handle "Day 2" of `inspektor_gadget_observability` tool. It adds upgrade action to allow users to upgrade Inspektor Gadget. Also, includes this version information in the `is_deployed` to hint for an upgrade. 
Other improvements include aligning gadget version with Inspektor Gadget version to ensure compatibility. Also, runtime now always uses the latest `kubeconfig` to ensure if user does `get-credentials` they don't need to restart the server and introducing lock formatter which we need as part of [new IG release](https://github.com/inspektor-gadget/inspektor-gadget/pull/4707). 
I have included some tests. Also, [asked copilot to do some testing.](https://gist.githubusercontent.com/mqasimsarfraz/da0a4b8c25337a4e257db89f9588a130/raw/bc3667224b61245712c962627dbdf9b …

chore/inspektor_gadget: Add upgrade action

---

Makefile
README.md

Hey guys, first off, I want to say I really appreciate the solution this project provides, and I definitely want to contribute to it further.
As a starting point, I’ve made a small but meaningful enhancement to improve local development reliability.
- **Updated Makefile to explicitly use bash with `-eo pipefail` for multi-line recipes**  
- By default, GNU Make uses `/bin/sh`, which often lacks `pipefail`. This means in multi-line recipes (like the `release` loop), a failing command in a pipeline may not cause the recipe to fail, leading to silent errors.  
- Our `PLATFORMS` list is static, but a local build can still fail (e.g., due to a changed third-party dependency). Setting `bash -eo pipefail` ensures each command in the loop fails fast, preventing partial or misleading build …

makefile/docs: enforce bash for multi-line targets and document in README

---

.slsa-goreleaser/darwin-amd64.yml
.slsa-goreleaser/darwin-arm64.yml
.slsa-goreleaser/linux-amd64.yml
.slsa-goreleaser/linux-arm64.yml
.slsa-goreleaser/windows-amd64.yml
.slsa-goreleaser/windows-arm64.yml
Dockerfile
Makefile
internal/config/config.go
internal/version/version.go

1. Hardcoded fallback version: The version.go file has GitVersion = "1" hardcoded
2. Docker builds don't inject version: The Dockerfile doesn't use ldflags to inject version info
3. SLSA builds missing ldflags: The goreleaser configs don't include version injection
4. Inconsistent version sources: Telemetry gets stale version info in containerized deployments
The version system has been improved to properly integrate with Git tags and GitHub releases, ensuring that telemetry and version reporting reflect the actual released version rather than hardcoded values.
**Problem**: Docker builds were not injecting version information via ldflags.
**Solution**: Updated `Dockerfile` to use build arguments for version injection:
```dockerfile
RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} …
```

Feat: Version System Improvements

---

internal/server/server.go
internal/server/server_test.go

Enhances user experience when accessing incorrect endpoints by providing:
- Custom 404 responses with JSON format for both SSE and streamable-http transports
- Clear guidance on correct MCP endpoint usage (/mcp, /sse, /message)
- Comprehensive test coverage for new HTTP server behavior
Fix #165

feat: add helpful 404 responses for HTTP/SSE server endpoints

---

README.md
internal/azcli/login.go
internal/azcli/login_test.go
internal/command/command.go
internal/server/server.go
internal/server/server_test.go

Resolves #147
- Added `internal/azcli/login.go`: a testable, injectable login module that auto‑detects and supports:
- Service principal
- Federated token
- User‑assigned & system‑assigned managed identities
- Updated `internal/server/server.go`:
- `initializeInfrastructure` now uses the new login logic.
- Allows injection of a custom `Proc` factory for process execution (facilitating testing).
- Tests:
- `internal/azcli/login_test.go` covers all auth flows and error cases with a mock `Proc`.
- `internal/server/server_test.go` now injects a fake Azure CLI process to avoid real CLI calls, improving reliability.
- Minor improvements:
- `internal/command/command.go` now returns both stderr and the error.
- Enhanced error wrapping in server init.
- Cleaned up test env‑var placeholders.

feat: implement azcli login functionality with multiple authentication methods

---

CONTRIBUTING.md
README.md

Close #180
- Add detailed CONTRIBUTING.md with development setup instructions
- Include local testing procedures with GitHub Copilot and Claude Desktop
- Document component-based architecture for adding new MCP tools
- Add testing guidelines for both CLI and SDK-based tools
- Update README.md with prominent link to contribution guide
- Provide quick start guide for new contributors

docs: add comprehensive contribution guides

---

README.md
go.mod
go.sum

mcp-kubernetes bumped to support switching kubectl context.

chore: bump k8s tools and fix the tool list in README

---

README.md

- Fixes ambiguous WSL guidance that causes ENOENT errors in Remote-WSL setups
- Replaces the current note with clear, separate instructions for two scenarios:
- **Windows host VS Code**: Use `"command": "wsl"` to invoke WSL binaries
- **Remote-WSL (VS Code inside WSL)**: Use direct binary paths or bash wrapper
- Adds troubleshooting section to help users identify their environment and resolve spawn errors
The current README section (lines 313-325) suggests using `"command": "wsl"` for "VS Code running inside WSL environment", but this is misleading and causes the exact ENOENT error described in the issue. The `wsl` command is a Windows-side launcher that's not available inside the WSL environment when using the Remote-WSL extension.
Closes #190

Fix README WSL guidance to prevent ENOENT errors (#190)

---

README.md

When running the server via MCP toolkit on docker-engine, users need to configure `container_user` to ensure the `gateway` works fine. Since the upstream PRs have been merged we can go ahead and include this in our doucmentation:
- https://github.com/docker/mcp-registry/pull/180
- https://github.com/docker/mcp-gateway/pull/104

chore: Add note for container_user

---

internal/components/azaks/registry.go
internal/tools/handler.go
internal/tools/handler_test.go

Currently, only exit code 1 is shown on tool call failure, so that MCP clients won't know why that fails.
This PR adds the error message as part of tool call result and also enriches the unit tests.

fix: ensure error messages are included in tool output

---

Dockerfile

This change adds [kubelogin](https://github.com/Azure/kubelogin) to the Dockerfile to allow clusters using Microsoft Entra authentication when using docker. 
```
$ az aks get-credentials --resource-group qasim-rg --name qasim-entra-cluster --overwrite-existing
$ kubelogin convert-kubeconfig -l azurecli
$ docker run --rm -it --user 1000 -v $HOME/.azure:/home/mcp/.azure -v $HOME/.kube/config:/home/mcp/.kube/config --entrypoint=bash mcp/aks
cb5b4ba3b033:~$ kubectl get pods
No resources found in default namespace.
```

feat: add kubelogin to Dockerfile
